name: Publish Firefox Addon (yayuyokitano/firefox-addon)

on:
  workflow_dispatch: # Trigger workflow manually
  release:
    types: [published] # Trigger when a new release is published

jobs:
  zip-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout # Checkout the repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Zip files
        uses: vimtor/action-zip@v1.2
        with:
          files: manifest.json icons/
          dest: result.zip

  publish:
    needs: zip-files
    runs-on: ubuntu-latest
    steps:
      - name: Publish
        uses: yayuyokitano/firefox-addon@v0.0.6-alpha
        with:
          api_key: ${{ secrets.FIREFOX_JWT_ISSUER }}
          api_secret: ${{ secrets.FIREFOX_JWT_SECRET }}
          guid: ${{ secrets.FIREFOX_EXTENSION_ID }}
          xpi_path: result.zip
          # xpi_path: firefox-brave-search.zip
          # src_path: firefox-brave-search-src.zip # Optional
