name: Publish Firefox Addon (new version)

on:
  workflow_dispatch:
  # push:
  #   branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: wdzeng/firefox-addon@v1
        with:
          addon-guid: "{53c0f15a-a430-4d4f-ac91-caed0d516155}"
          xpi-path: your-addon.zip
          self-hosted: false
          jwt-issuer: ${{ secrets.FIREFOX_JWT_ISSUER }}
          jwt-secret: ${{ secrets.FIREFOX_JWT_SECRET }}
