name: "Build"

on:
  workflow_dispatch:
  # pull_request:
  # push:
  #   branches:
  #     - main

jobs:
  build:
    name: "Build"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v1

      - name: "web-ext build"
        id: web-ext-build
        uses: kewisch/action-web-ext@v1
        with:
          cmd: build
          # source: src
          filename: "{name}-{version}.xpi"
          ignoreFiles: '[ "package.json","package-lock.json","yarn.lock", ".github", ".gitattributes", "LICENSE", "README.md" ]'

      - name: "Upload Artifact"
        uses: actions/upload-artifact@v3
        with:
          name: target.xpi
          path: ${{ steps.web-ext-build.outputs.target }}
